### ISSUE TITLE
Improved Node-RED support for GrovePi

### ISSUE THREAD

**Issue by chrowe** [DexterInd/Raspbian_For_Robots#168]
It is great that Node-RED ships with R4R but it doesn't work with the GrovePi out of the box. It would be great if R4R could come with a newer version of Node-RED and a working GrovePi library installed.
## Node-RED 
 - version installed = v0.14.6
 - current version = v0.18.4 https://github.com/node-red/node-red/releases

## GrovePi Node-RED packages
 - https://flows.nodered.org/node/node-red-contrib-grovepi
 - https://flows.nodered.org/node/node-red-grovepi-nodes
 - https://flows.nodered.org/node/node-red-node-grovepi

I have not tried all these yet but I hope at least one works

**Comment by chrowe** [comment]
I guess Node-RED is just part of Raspian. Any plans to upgrade R4R to run on top of Raspian Stretch? That comes with Node-RED v0.17.4 at least.

**Comment by chrowe** [comment]
In the short term, it looks like running the official Node-RED Raspberry Pi install script from https://nodered.org/docs/hardware/raspberrypi gives you npm and Node-RED v0.18.4 which in turn enables the "Manage palette" option in the menu. From there you can install any of the above packages. I used https://flows.nodered.org/node/node-red-contrib-grovepi and it worked as expected!

**Comment by CleoQc** [comment]
That's great that it worked! None of us on the team have any experience with Node-RED so this is useful information to us!
Thanks a lot!

**Comment by DragonPigGQ** [comment]
Hi, while i was installing node-red-contrib-grovepi, the following errors occur,
2019-11-23T15:35:44.962Z [err] ERR! build error
2019-11-23T15:35:44.963Z [err]  
2019-11-23T15:35:44.966Z [err] gyp
2019-11-23T15:35:44.966Z [err]  ERR!
2019-11-23T15:35:44.966Z [err]  stack
2019-11-23T15:35:44.967Z [err]  Error: `make` failed with exit code: 2
2019-11-23T15:35:44.967Z [err] gyp 
2019-11-23T15:35:44.967Z [err] ERR! stack
2019-11-23T15:35:44.968Z [err]      at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2019-11-23T15:35:44.968Z [err] gyp 
2019-11-23T15:35:44.969Z [err] ERR! 
2019-11-23T15:35:44.969Z [err] stack     at ChildProcess.emit (events.js:210:5)
2019-11-23T15:35:44.969Z [err] gyp
2019-11-23T15:35:44.969Z [err]  ERR!
2019-11-23T15:35:44.970Z [err]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2019-11-23T15:35:44.971Z [err] gyp
2019-11-23T15:35:44.971Z [err]  ERR! 
2019-11-23T15:35:44.972Z [err] System Linux 4.19.42-v7+
2019-11-23T15:35:44.972Z [err] gyp
2019-11-23T15:35:44.972Z [err]  ERR!
2019-11-23T15:35:44.973Z [err]  command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-11-23T15:35:44.973Z [err] gyp 
2019-11-23T15:35:44.973Z [err] ERR! 
2019-11-23T15:35:44.974Z [err] cwd /home/pi/.node-red/node_modules/buffertools
2019-11-23T15:35:44.974Z [err] gyp 
2019-11-23T15:35:44.974Z [err] ERR! 
2019-11-23T15:35:44.975Z [err] node -v v12.13.1
2019-11-23T15:35:44.975Z [err] gyp ERR!
2019-11-23T15:35:44.975Z [err]  node-gyp -v
2019-11-23T15:35:44.976Z [err]  v5.0.5
2019-11-23T15:35:44.976Z [err] gyp
2019-11-23T15:35:44.976Z [err]  ERR! 
2019-11-23T15:35:44.977Z [err] not ok 
2019-11-23T15:35:45.819Z [err] npm ERR! code ELIFECYCLE
2019-11-23T15:35:45.819Z [err] npm ERR! errno 1
2019-11-23T15:35:45.819Z [err] npm ERR! buffertools@2.1.6 install: `node-gyp rebuild`
2019-11-23T15:35:45.819Z [err] npm ERR! Exit status 1
2019-11-23T15:35:45.819Z [err] npm ERR! 
2019-11-23T15:35:45.819Z [err] npm ERR! Failed at the buffertools@2.1.6 install script.
2019-11-23T15:35:45.819Z [err] npm ERR!
2019-11-23T15:35:45.820Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-11-23T15:35:45.879Z [err] 
2019-11-23T15:35:45.879Z [err] npm ERR! A complete log of this run can be found in:
2019-11-23T15:35:45.879Z [err] npm ERR!
2019-11-23T15:35:45.880Z [err]      /home/pi/.npm/_logs/2019-11-23T15_35_45_835Z-debug.log


Anyideas on why it this happening? I have reinstalled node-red based on the documentation in https://nodered.org/docs/getting-started/raspberrypi . But it is still not working :frowning: :frowning:
